# Generated by Django 3.2.5 on 2024-03-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_auto_20240321_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_collaborator',
            field=models.BooleanField(default=False),
        ),
    ]
