# Generated by Django 3.2.5 on 2024-03-23 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_user_is_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
