# Generated by Django 3.2.5 on 2024-03-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_auto_20240323_0914'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaborator',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='project',
        ),
    ]
