# Generated by Django 3.2.5 on 2024-03-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_auto_20240325_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborator',
            field=models.ManyToManyField(blank=True, related_name='projects', to='taskapp.Collaborator', verbose_name='Collaborators'),
        ),
    ]
