# Generated by Django 3.2.5 on 2024-03-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0009_auto_20240325_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='assignees',
        ),
    ]
