# Generated by Django 5.0.6 on 2024-10-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0010_remove_subtask_assignees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
