# Generated by Django 5.0.6 on 2024-10-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0011_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
