# Generated by Django 5.0.6 on 2024-10-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0012_invitation_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='email',
        ),
    ]
